import Ecto.Query

alias NorthwindElixirTraders.Repo
alias NorthwindElixirTraders.Category
alias NorthwindElixirTraders.Employee
alias NorthwindElixirTraders.Supplier
alias NorthwindElixirTraders.Product
